everythingyourself/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('create/', include('videoCreator.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videoCreator/urls.py
from django.urls import path


from . import views

app_name = 'createVideo'
urlpatterns = [
    path('create/<int:id>', views.video_create, name='video_create'),
    path('crop/<int:id>/', views.image_crop, name='image_crop'),
    path('', views.image_upload, name='image_upload'),
]

videoCreator/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

class VideoTemplate(models.Model):
    name = models.CharField(max_length=100)
    background_clip = models.FileField()
    faces_count = models.IntegerField()

class FaceInsert(models.Model):
    template = models.ForeignKey(VideoTemplate, on_delete=models.PROTECT)
    creation_datetime = models.DateTimeField(auto_now_add=True)

videoCreator/forms.py
from django import forms

class UploadFaceForm(forms.Form):
    face = forms.ImageField(label="Ihr Gesicht")


class CropFaceForm(forms.Form):
    imagefield = forms.CharField(label="Cropped Face")

videoCreator/views.py
from mimetypes import guess_type
import os
import base64
import django_heroku
import time
from channels.layers import get_channel_layer
import asyncio
from asgiref.sync import async_to_sync

from django.http import HttpResponse
from django.shortcuts import render
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.http.request import HttpRequest
from django.shortcuts import redirect

from .video  import render_video
from .forms import UploadFaceForm, CropFaceForm
from .models import VideoTemplate, FaceInsert
from .consumers import VideoConsumer

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def video_create(request, id, fps=60):
    """
    Triggers video rendering method in external python file
    :param request: Request that triggers rendering
    :param id: ID of image/face
    :param fps: How many frames per second (default is 60)
    :return: Returns the file (video) as a "download"
    """
    """
    Calls function to render video and returns path to it.
    :param id: ID of face insert instance
    :param fps: frames per second of
    :return: video
    """
    videofile = render_video(id, fps=60)
    video_path = os.path.join(BASE_DIR, videofile)

    with open(video_path, 'rb') as f:
        response = HttpResponse(f, content_type='video/mp4')
        response['Content-Length'] = len(response.content)
        response['Content-Disposition'] = 'attachment; filename=export-face.mp4'
        return response


def image_upload(request):
    """
    On GET renders the upload form.
    On POST takes file, matches to template-video, saves the file in specific directory and redirects the user to
    a page to crop his image
    :param request: Request that triggers page/upload
    :return: Returns a redirect to cropping-page
    """
    if request.method == 'POST':
        form = UploadFaceForm(request.POST, request.FILES)
        if form.is_valid():
            template = VideoTemplate.objects.get(id="1")

            insert = FaceInsert(template=template)
            insert.save()
            id = insert.id

            data = request.FILES['face']
            filename = 'original-img_{}'.format(id)
            tmp_path = 'faces/{}.png'.format(filename)
            path = default_storage.save(tmp_path, ContentFile(data.read()))

            is_production = os.environ.get('PRODUCTION', False)
            host = HttpRequest.get_host(request)
            if is_production:
                redirect_url = 'https://{}/create/crop/{}'.format(host, id)
                print("what you doing")
            else:
                redirect_url = 'http://{}/create/crop/{}'.format(host, id)
            return redirect(redirect_url)

    uploadfaceform = UploadFaceForm()
    return render(request, 'videoCreator/image_upload.html', {'UploadFaceForm': uploadfaceform})


def image_crop(request, id):
    """
    On GET renders page to crop the image, giving the correct path in the media directory.
    On POST takes in base64 image, converts to png file and saves it; redirects to creation of video.
    :param request: Request that triggers page/cropping
    :param id: ID of image/face
    :return: Returns appropriate cropping form, or please-wait modal during video creation.
    """
    is_production = os.environ.get('PRODUCTION', False)
    if request.method == 'POST':
        pass
        # channel_layer = get_channel_layer()
        # async_to_sync(channel_layer.group_send(
        #     str(id),
        #     {"type": "channel_message", "text": "hey"},
        # ))
        #time.sleep(60)
        # form = CropFaceForm(request.POST, request.FILES)
        # if form.is_valid():
        #     data = form.cleaned_data['imagefield']
        #     formatinfo, imgstring = data.split(';base64,')
        #     ext = formatinfo.split('/')[-1]
        #
        #     image = ContentFile(base64.b64decode(imgstring), name='temp.' + ext)
        #     filename = 'cropped-img_{}'.format(id)
        #     tmp_path = 'faces/{}.png'.format(filename)
        #     path = default_storage.save(tmp_path, image)
        #
        #     host = HttpRequest.get_host(request)
        #     if is_production:
        #         redirect_url = 'https://{}/create/create/{}'.format(host, id)
        #     else:
        #         redirect_url = 'http://{}/create/create/{}'.format(host, id)
        #     return redirect(redirect_url)

    filename = 'original-img_{}'.format(id)
    host = HttpRequest.get_host(request)
    if is_production:
        path = 'https://{}/media/faces/{}.png'.format(host, filename)
    else:
        path = 'http://{}/media/faces/{}.png'.format(host, filename)
    # path = os.path.join(BASE_DIR, tmp_path)

    return render(request, 'videoCreator/image_crop.html', {'imgsrc': path, 'id': id})

everythingyourself/videoCreator/templates/videoCreator/create_video.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Video</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
    <script>
        function getRoundedCanvas(sourceCanvas) {
          var canvas = document.createElement('canvas');
          var context = canvas.getContext('2d');
          var width = sourceCanvas.width;
          var height = sourceCanvas.height;

          canvas.width = width;
          canvas.height = height;
          context.imageSmoothingEnabled = true;
          context.drawImage(sourceCanvas, 0, 0, width, height);
          context.globalCompositeOperation = 'destination-in';
          context.beginPath();
          context.arc(width / 2, height / 2, Math.min(width, height) / 2, 0, 2 * Math.PI, true);
          context.fill();
          return canvas;
        }

        function createCropper() {
          var image = document.getElementById('image');
          console.log(image);
          var button = document.getElementById('button');
          var result = document.getElementById('result');
          var croppable = false;
          var cropper = new Cropper(image, {
            aspectRatio: 1,
            viewMode: 1,
            ready: function () {
              croppable = true;
            },
          });
          console.log(cropper);

          button.onclick = function () {
            var croppedCanvas;
            var roundedCanvas;
            var roundedImage;

            if (!croppable) {
              return;
            }

            // Crop
            croppedCanvas = cropper.getCroppedCanvas();

            // Round
            roundedCanvas = getRoundedCanvas(croppedCanvas);

            // Show
            roundedImage = document.createElement('img');
            roundedImage.src = roundedCanvas.toDataURL()
            result.innerHTML = '';
            result.appendChild(roundedImage);
            };
        };


        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#image')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(200);
                };

                reader.readAsDataURL(input.files[0]);
                createCropper();
            }
        };

    </script>
</head>
<body>
    <h1>Here you can insert your face into a demo video!</h1>
    <form action="/create/" method="post"  enctype="multipart/form-data">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        <p><label for="id_face">Ihr Gesicht:</label> <input type="file" name="face" accept="image/*" required id="id_face" onchange="readURL(this);"></p>
        <img id="image" src="#" alt="Bitte ein Bild auswählen!" />
        <br/><img id="imgex" src="/static/face.png" alt="">
        <h3>Resultat</h3>
        <p>
          <button type="button" id="button">Ausschneiden</button>
        </p>
        <div id="result"></div>
        <br/><input type="submit" value="Absenden" id="submit">

    </form>

    <form>

    </form>
</body>
</html>

videoCreator/templates/videoCreator/image_crop.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Crop Image</title>
    <script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
    <link  href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.js"></script>
    <script src="https://unpkg.com/micromodal/dist/micromodal.min.js"></script>
    <style>
    .container {
      max-width: 640px;
    }

    img {
      max-width: 100%;
    }

    .cropper-view-box,
    .cropper-face {
      border-radius: 50%;
    }
    #download_btn {
      display: none;
    }

    /**************************\
  Basic Modal Styles
\**************************/

.modal {
  font-family: -apple-system,BlinkMacSystemFont,avenir next,avenir,helvetica neue,helvetica,ubuntu,roboto,noto,segoe ui,arial,sans-serif;
}

.modal__overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0,0,0,0.6);
  display: flex;
  justify-content: center;
  align-items: center;
}

.modal__container {
  background-color: #fff;
  padding: 30px;
  max-width: 500px;
  max-height: 100vh;
  border-radius: 4px;
  overflow-y: auto;
  box-sizing: border-box;
}

.modal__header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.modal__title {
  margin-top: 0;
  margin-bottom: 0;
  font-weight: 600;
  font-size: 1.25rem;
  line-height: 1.25;
  color: #00449e;
  box-sizing: border-box;
}

.modal__close {
  background: transparent;
  border: 0;
}

.modal__header .modal__close:before { content: "\2715"; }

.modal__content {
  margin-top: 2rem;
  margin-bottom: 2rem;
  line-height: 1.5;
  color: rgba(0,0,0,.8);
}

.modal__btn {
  font-size: .875rem;
  padding-left: 1rem;
  padding-right: 1rem;
  padding-top: .5rem;
  padding-bottom: .5rem;
  background-color: #e6e6e6;
  color: rgba(0,0,0,.8);
  border-radius: .25rem;
  border-style: none;
  border-width: 0;
  cursor: pointer;
  -webkit-appearance: button;
  text-transform: none;
  overflow: visible;
  line-height: 1.15;
  margin: 0;
  will-change: transform;
  -moz-osx-font-smoothing: grayscale;
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
  -webkit-transform: translateZ(0);
  transform: translateZ(0);
  transition: -webkit-transform .25s ease-out;
  transition: transform .25s ease-out;
  transition: transform .25s ease-out,-webkit-transform .25s ease-out;
}

.modal__btn:focus, .modal__btn:hover {
  -webkit-transform: scale(1.05);
  transform: scale(1.05);
}

.modal__btn-primary {
  background-color: #00449e;
  color: #fff;
}



/**************************\
  Demo Animation Style
\**************************/
@keyframes mmfadeIn {
    from { opacity: 0; }
      to { opacity: 1; }
}

@keyframes mmfadeOut {
    from { opacity: 1; }
      to { opacity: 0; }
}

@keyframes mmslideIn {
  from { transform: translateY(15%); }
    to { transform: translateY(0); }
}

@keyframes mmslideOut {
    from { transform: translateY(0); }
    to { transform: translateY(-10%); }
}

.micromodal-slide {
  display: none;
}

.micromodal-slide.is-open {
  display: block;
}

.micromodal-slide[aria-hidden="false"] .modal__overlay {
  animation: mmfadeIn .3s cubic-bezier(0.0, 0.0, 0.2, 1);
}

.micromodal-slide[aria-hidden="false"] .modal__container {
  animation: mmslideIn .3s cubic-bezier(0, 0, .2, 1);
}

.micromodal-slide[aria-hidden="true"] .modal__overlay {
  animation: mmfadeOut .3s cubic-bezier(0.0, 0.0, 0.2, 1);
}

.micromodal-slide[aria-hidden="true"] .modal__container {
  animation: mmslideOut .3s cubic-bezier(0, 0, .2, 1);
}

.micromodal-slide .modal__container,
.micromodal-slide .modal__overlay {
  will-change: transform;
}
  </style>
        <script>

        function getRoundedCanvas(sourceCanvas) {
          var canvas = document.createElement('canvas');
          var context = canvas.getContext('2d');
          var width = sourceCanvas.width;
          var height = sourceCanvas.height;

          canvas.width = width;
          canvas.height = height;
          context.imageSmoothingEnabled = true;
          context.drawImage(sourceCanvas, 0, 0, width, height);
          context.globalCompositeOperation = 'destination-in';
          context.beginPath();
          context.arc(width / 2, height / 2, Math.min(width, height) / 2, 0, 2 * Math.PI, true);
          context.fill();
          return canvas;
        }
        $(document).ready(function() {
  //MicroModal.init();
  const id = document.getElementById('id_nr').textContent;

      const ws = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/videoprogress/'
            + id
            + '/'
        );
       ws.onopen = function () {
       ws.send({message: "pong"});
       };

      ws.onmessage = function(e) {
            alert("jej")
            //const is_ready = JSON.parse(e.is_ready);
            //if(is_ready == True){
            //    document.getElementById("download_btn").style.display = "inline";
            // }
        };

});

      window.addEventListener('DOMContentLoaded', function () {
      var image = document.getElementById('image');
      var button = document.getElementById('button');
      var result = document.getElementById('result');
      var croppable = false;
      var cropper = new Cropper(image, {
        aspectRatio: 1,
        viewMode: 1,
        ready: function () {
          croppable = true;
        },
      });

      button.onclick = function () {
        var croppedCanvas;
        var roundedCanvas;
        var roundedImage;

        if (!croppable) {
          return;
        }

        // Crop
        croppedCanvas = cropper.getCroppedCanvas();

        // Round
        roundedCanvas = getRoundedCanvas(croppedCanvas);

        // Show
        roundedImage = document.createElement('img');
        roundedImage.src = roundedCanvas.toDataURL()
        result.innerHTML = '';
        result.appendChild(roundedImage);

        document.getElementsByName("imagefield")[0].setAttribute("value", roundedImage.src);

        document.getElementById("submit").style.display = "inline";

      };
    });
    </script>
</head>
<body>
    <h1>Crop The Image</h1>
    <p>Nr.</p><p id="id_nr">{{id}}</p>
    <div style="max-height: 400px;">
      <img src="{{imgsrc}}" alt="" id="image" height="auto" width="100%">
    </div>
    <p><button type="button" id="button">Ausschneiden</button></p>
    <div id="result"></div>
    <form action="/create/crop/{{id}}/" method="post" enctype="multipart/form-data" data-micromodal-trigger="modal-1">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        <input type="hidden" name="imagefield">
        <input type="submit" value="Absenden" id="submit" style="display:none;">
    </form>

<div class="modal micromodal-slide" id="modal-1" aria-hidden="true">
  <div class="modal__overlay" tabindex="-1" data-micromodal-close>
    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="modal-1-title">
      <header class="modal__header">
        <h2 class="modal__title" id="modal-1-title">
          Hinweis
        </h2>
        <button class="modal__close" aria-label="Close modal" data-micromodal-close></button>
      </header>
      <main class="modal__content" id="modal-1-content">
        <p>
        Das Video wird nun geschnitten! Einfach kurz warten. Sobald das Video fertig ist,
            erscheint hier ein Download-Button.
        </p>
        <button id="download_btn">Video herunterladen</button>
      </main>
      <footer class="modal__footer">
        <button class="modal__btn" data-micromodal-close aria-label="Close this dialog window">Schließen</button>
      </footer>
    </div>
  </div>
</div>

</body>
</html>

videoCreator/templates/videoCreator/image_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Video</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#image')
                        .attr('src', e.target.result)
                        .width(auto)
                        .height(auto);
                };

                reader.readAsDataURL(input.files[0]);
            }
        };

    </script>
</head>
<body>
    <h1>Here you can insert your face into a demo video!</h1>
    <form action="/create/" method="post"  enctype="multipart/form-data">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        <p><label for="id_face">Ihr Gesicht:</label> <input type="file" name="face" accept="image/*" required id="id_face" onchange="readURL(this);"></p>
        <img id="image" src="#" alt="Bitte ein Bild auswählen!" />
        <br/><input type="submit" value="Absenden" id="submit">
    </form>

    <form>

    </form>
</body>
</html>

videoCreator/templates/videoCreator/video_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Video Creation</title>
</head>
<body>
    <h1>Please wait, the video is being created!</h1>
</body>
</html>